name: jsonata_flutter_example
description: "Demonstrates how to use the jsonata_flutter plugin."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  jsonata_flutter:
    path: ../../jsonata_flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true